### PR TITLE
version bump to 1.9.1

### PR DESCRIPTION
**Pull request by djsutherland**

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks!

**Comment by jakevdp** [comment]
Hi @dougalsutherland – it seems you're pretty on top of pyflann releases. Would you be interested in joining the pyflann conda-forge team so you can review and merge pull requests yourself?

**Comment by djsutherland** [comment]
Sure, I'd be happy to do that -- though I think flann 1.9.1 will be the last release for the foreseeable future so it probably won't matter too much.

**Comment by jakirkham** [comment]
Agreed would be happy to have you on both `flann` and `pyflann`. FWIW if other issues (pinning changes, build problems, etc.) come up it would still be nice to have your expertise even if it is not release related. :)

**Comment by jakevdp** [comment]
@jakirkham it looks like you're the maintainer on both teams, so you can add @dougalsutherland :smile:

**Comment by jakirkham** [comment]
Will happily merge PRs for both. 😄

**Pull request merged**
